# Generated by Django 3.2 on 2021-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='p_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
