# Generated by Django 3.2 on 2021-05-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0002_projects_p_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='creativity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='dam',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='execution',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='presentation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projects',
            name='research_question',
            field=models.IntegerField(default=0),
        ),
    ]
