# Generated by Django 3.2 on 2021-05-29 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0003_auto_20210529_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='judge',
            field=models.CharField(default='Not judged yet', max_length=64),
        ),
    ]
